@AdvanceApi_HostAddress = http://localhost:5030

GET {{AdvanceApi_HostAddress}}/weatherforecast/
Accept: application/json

###

# Sessions API - Obtener conteo de sesiones activas
GET {{AdvanceApi_HostAddress}}/api/Sessions/active-count/testuser
Accept: application/json

###
